### ISSUE TITLE
No version of MediaWikiAuth works out of the box with latest MediaWiki (1.36.1)

### ISSUE THREAD

**Issue by ineffyble** [SkizNet/mediawiki-MediaWikiAuth#1]
Tried to set this up and ended up having to hack the code a bit.

The version that's currently in `master` in git, which claims to be `1.4.0`, is broken because it has references to `ReattributeEdits::useActorSchema` in `maintenance/reattributeImportedEdits.php` and `includes/ExternalWikiPrimaryAuthenticationProvider.php`, but that method does not exist in the actual class itself.

When I disabled the reattribution feature, I then encountered an issue where the remote login was succeeding, but subsequent calls to the API (to retrieve watchlist and profile info) were throwing unauthenticated errors. I investigated and found that the manual cookie handling was only storing the first `Set-Cookie` from each request in the cookie jar, and that the remote MediaWiki installation running MediaWiki 1.32.0 was sending multiple cookies that it expected me to present. I saw in the comments that the manual cookie handling was because of an issue with Guzzle in past versions of MediaWiki, but my solution was to comment out the handling and let the built-in handling happen, and that seemed to resolve the issue.

The release that's available for tar/zip download via `MWUsers` is `1.3.0`, but on MediaWiki 1.36.1 it throws errors, trying to call a non-existent method on the MediaWiki `User` class. 

I'm a little puzzled about what versions exist. MediaWiki only links here, where there's no tags or releases (and it looks like it was migrated), and to MWUsers, which only has `1.3.0`. That said, MediaWiki lists the latest stable release as `1.3.1`, and looking at past commits it sounds like a `1.3.7` exists (and presumably the ones between).

**Comment by skizzerz** [comment]
CI should now verify that things aren't completely broken on supported MW versions. 1.36 itself is no longer supported, but a lot of work was put in to fix operation on recent versions.
